/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module Mux_2x1
(
    input [0:0] sel,
    input in_0,
    input in_1,
    output reg out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule


module DIG_Register_BUS #(
    parameter Bits = 1
)
(
    input C,
    input en,
    input [(Bits - 1):0]D,
    output [(Bits - 1):0]Q
);

    reg [(Bits - 1):0] state = 'h0;

    assign Q = state;

    always @ (posedge C) begin
        if (en)
            state <= D;
   end
endmodule

module Mux_4x1
(
    input [1:0] sel,
    input in_0,
    input in_1,
    input in_2,
    input in_3,
    output reg out
);
    always @ (*) begin
        case (sel)
            2'h0: out = in_0;
            2'h1: out = in_1;
            2'h2: out = in_2;
            2'h3: out = in_3;
            default:
                out = 'h0;
        endcase
    end
endmodule


// Register for storing large constants.
// There is a 1-bit command describing this register. 
// In this way, 15 bits can be stored (the 16th bit 
// activates the writing of this register and therefore 
// is always one). The 16th bit will be set according 
// to the 'immediate extend mode' (iem).
module ImReg (
  input en, // enables storage
  input [1:0] iem, // immediate extend mode (0: sign extend; 1: extend with 0, 2:extend with S0, 3:extend with D0)
  input C,
  input [15:0] inst, // the current instruction
  output [15:0] imm // The constant of register contents and bit 8.

);
  wire [14:0] s0;
  wire [14:0] s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  assign s2 = inst[0];
  assign s3 = inst[4];
  assign s0 = inst[14:0];
  // imm
  DIG_Register_BUS #(
    .Bits(15)
  )
  DIG_Register_BUS_i0 (
    .D( s0 ),
    .C( C ),
    .en( en ),
    .Q( s1 )
  );
  assign s5 = s1[14];
  Mux_4x1 Mux_4x1_i1 (
    .sel( iem ),
    .in_0( s5 ),
    .in_1( 1'b0 ),
    .in_2( s2 ),
    .in_3( s3 ),
    .out( s4 )
  );
  assign imm[14:0] = s1;
  assign imm[15] = s4;
endmodule
module Register1
  (
    input D,
    input C,
    input en,
    input rst_n,
    output Q
  );

  reg  state;

  assign Q = state;

  always @ (negedge C, negedge rst_n)
  begin

    if(!rst_n)
    begin
      state <= 1'h0;
    end
    else
      if (en)
        state <= D;

  end
endmodule


module register_1bit (
  input D,
  input C,
  input en,
  input rst,
  output Q
);
  // Register1
  Register1 Register1_i0 (
    .D( D ),
    .C( C ),
    .en( en ),
    .rst_n( rst ),
    .Q( Q )
  );
endmodule
module Register8
  (
    input [7:0]D,
    input C,
    input en,
    input rst_n,
    output [7:0]Q
  );

  reg [7:0] state ;

  assign Q = state;

  always @ (posedge C or negedge rst_n)
  begin
    if(!rst_n)
    begin
      state <= 8'h0;
    end
    else
      if (en)
        state <= D;


  end
endmodule


module register_8bit (
  input [7:0] D,
  input C,
  input en,
  input rst,
  output [7:0] Q
);
  // Register8
  Register8 Register8_i0 (
    .D( D ),
    .C( C ),
    .en( en ),
    .rst_n( rst ),
    .Q( Q )
  );
endmodule
module programCounter
(
    input  wire [15:0] AluIn,
    input  wire        clk,
    input  wire        rst_n,
    input  wire        pc_en,
    input  wire        absJmp,
    input  wire        intr,
    input  wire        reti,
    input  wire        relJmp,
    output wire [15:0] Nextpc,
    output wire [15:0] PC
);

 localparam [15:0] interuptFuncAdr = 16'h0002;
  reg [15:0] interruptAdress;

  reg [15:0] PCr;
  reg [15:0] Nextpcr;

  assign Nextpc = Nextpcr;
  assign PC     = PCr;

  always @(posedge clk , negedge rst_n)
  begin
    if (!rst_n)
    begin
      PCr     <= 16'h0000;
      Nextpcr <= 16'h0001;
      interruptAdress <= 16'h0000;
    end
    else if (pc_en)
    begin
      if (reti)
      begin
        PCr     <= interruptAdress + 16'd1;
        Nextpcr <= interruptAdress + 16'd2;
      end
      else if (intr)
      begin
        if (relJmp || absJmp)
          interruptAdress <= PCr - 16'd1;
        else
          interruptAdress <= PCr;

        PCr     <= interuptFuncAdr;
        Nextpcr <= interuptFuncAdr + 16'd1;
      end
      else if (relJmp)
      begin
        PCr     <= PCr + AluIn + 16'd1;
        Nextpcr <= Nextpcr + AluIn + 16'd1;
      end
      else if (absJmp)
      begin
        PCr     <= AluIn;
        Nextpcr <= AluIn + 16'd1;
      end
      else
      begin
        PCr     <= PCr + 16'd1;
        Nextpcr <= Nextpcr + 16'd1;
      end
    end
  end

endmodule

module Mux_2x1_NBits #(
    parameter Bits = 2
)
(
    input [0:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule

module memory_wait_controller
(
    input  wire        clk,
    input  wire        rst_n,

    // CPU side
    input  wire        fetch_req,
    input  wire        ld_req,
    input  wire        st_req,
    input  wire [15:0] fetch_addr,
    input  wire [15:0] data_addr,
    input  wire [15:0] store_data,

    output reg  [15:0] mem_rdata,
    output reg         fetch_done,
    output reg         data_done,
    output reg         mem_stall,

    // SPI engine side
    output reg         spi_st,
    output reg         spi_ld,
    output reg  [15:0] spi_addr,
    output reg  [15:0] spi_data_in,
    output reg         spi_target,   // 0 = flash, 1 = ram

    input  wire [15:0] spi_data_out,
    input  wire        spi_busy
);

  localparam OP_NONE  = 2'd0;
  localparam OP_FETCH = 2'd1;
  localparam OP_LOAD  = 2'd2;
  localparam OP_STORE = 2'd3;

  localparam S_IDLE           = 3'd0;
  localparam S_START          = 3'd1;
  localparam S_WAIT_BUSY_HIGH = 3'd2;
  localparam S_WAIT_BUSY_LOW  = 3'd3;
  localparam S_FINISH         = 3'd4;

  reg [2:0] state;
  reg [1:0] op;

  always @(posedge clk , negedge rst_n)
  begin
    if (!rst_n)
    begin
      state       <= S_IDLE;
      op          <= OP_NONE;

      mem_rdata   <= 16'h0000;
      fetch_done  <= 1'b0;
      data_done   <= 1'b0;
      mem_stall   <= 1'b0;

      spi_st      <= 1'b0;
      spi_ld      <= 1'b0;
      spi_addr    <= 16'h0000;
      spi_data_in <= 16'h0000;
      spi_target  <= 1'b0;
    end
    else
    begin
      fetch_done <= 1'b0;
      data_done  <= 1'b0;
      spi_st     <= 1'b0;
      spi_ld     <= 1'b0;

      case (state)
        S_IDLE:
        begin
          mem_stall <= 1'b0;
          op        <= OP_NONE;

          if (st_req)
          begin
            op          <= OP_STORE;
            spi_target  <= 1'b1;      // RAM
            spi_addr    <= data_addr;
            spi_data_in <= store_data;
            mem_stall   <= 1'b1;
            state       <= S_START;
          end
          else if (ld_req)
          begin
            op          <= OP_LOAD;
            spi_target  <= 1'b1;      // RAM
            spi_addr    <= data_addr;
            spi_data_in <= 16'h0000;
            mem_stall   <= 1'b1;
            state       <= S_START;
          end
          else if (fetch_req)
          begin
            op          <= OP_FETCH;
            spi_target  <= 1'b0;      // FLASH
            spi_addr    <= fetch_addr;
            spi_data_in <= 16'h0000;
            mem_stall   <= 1'b1;
            state       <= S_START;
          end
        end

        S_START:
        begin
          if (op == OP_STORE)
            spi_st <= 1'b1;
          else if (op == OP_LOAD || op == OP_FETCH)
            spi_ld <= 1'b1;

          state <= S_WAIT_BUSY_HIGH;
        end

        S_WAIT_BUSY_HIGH:
        begin
          if (spi_busy)
            state <= S_WAIT_BUSY_LOW;
        end

        S_WAIT_BUSY_LOW:
        begin
          if (!spi_busy)
          begin
            if (op == OP_LOAD || op == OP_FETCH)
              mem_rdata <= spi_data_out;

            state <= S_FINISH;
          end
        end

        S_FINISH:
        begin
          mem_stall <= 1'b0;

          if (op == OP_FETCH)
            fetch_done <= 1'b1;
          else
            data_done <= 1'b1;

          state <= S_IDLE;
        end

        default:
        begin
          state <= S_IDLE;
        end
      endcase
    end
  end

endmodule
module spi_memory_interface (
    input  wire        clk,           // System clock
    input  wire        spi_rst_n,       // Reset
    input  wire        st,            // Store (write) signal
    input  wire        ld,            // Load (read) signal
    input  wire [15:0] addr,          // 16-bit memory address
    input  wire [15:0] data_in,       // 16-bit data input (for write)
    output reg  [15:0] data_out,      // 16-bit data output (for read)
    input  wire        is_continous,  // Continuous transaction flag
    output reg         spi_cs,        // SPI Chip Select (Active Low)
    output reg         spi_clk,       // SPI Clock
    output reg         busy,          // Busy signal
    output reg         spi_mosi,      // SPI MOSI (Master Out Slave In)
    input  wire        spi_miso      // SPI MISO (Master In Slave Out)

  );

  // Define FSM states

  localparam  IDLE = 4'b0000;
  localparam  START = 4'b0001;
  localparam  SEND_CMD = 4'b0010;
  localparam  SEND_ADDR = 4'b0011;
  localparam  WRITE_DATA = 4'b0100;
  localparam  READ_DATA = 4'b0101;
  localparam  STOP = 4'b0110;
  localparam  TOGGLECLKON = 4'b0111;
  localparam  decideFate = 4'b1000;

  localparam  STcom = 1;
  localparam  LDcom = 0;


  reg[4:0] state;
  reg[4:0] last_state;
  reg command;

  reg [7:0] shift_reg; // Shift register for SPI data
  reg [5:0] bit_cnt;   // Bit counter
  reg [2:0] byte_cnt;  // Byte counter
  reg [15:0] recv_data;// Temporary storage for received data

  reg [0:0] prev_command;
  reg [15:0] prev_addr;
  reg prev_is_continous;

  always @(posedge clk , negedge spi_rst_n)
  begin

    if (!spi_rst_n)
    begin
      state   <= IDLE;
      spi_cs  <= 1'b1;
      spi_clk <= 1'b0;
      spi_mosi <= 1'b0;
      busy    <= 1'b0;
      bit_cnt <= 3'b000;
      byte_cnt <= 3'b000;
      command <= STcom;
      state <= IDLE;
      last_state <= IDLE;
    end
    else
    begin
      case (state)
        IDLE:
        begin
          busy <= 1'b0;
          if (st || ld)
          begin
            state <= START;
            busy <= 1'b1;

            prev_command <= command;
            prev_addr <= addr;
            prev_is_continous <= is_continous;

            if (st)
            begin
              shift_reg <= 8'h02; // Write command
              command <= STcom;
            end

            else if (ld)
            begin
              shift_reg <= 8'h03; // Read command
              command <= LDcom;
            end

          end
        end

        START:
        begin
          spi_cs <=1'b0;
          bit_cnt <= 3'b000;
          byte_cnt <= 3'b000;
          state <= SEND_CMD;
        end

        SEND_CMD:
        begin
          spi_clk <= 0;
          if (bit_cnt < 8)
          begin
            spi_mosi <= shift_reg[7];  // Send MSB first
            shift_reg <= shift_reg << 1; // Shift left
            last_state <= state;

            state <= TOGGLECLKON;
            bit_cnt <= bit_cnt + 1;
          end
          else
          begin
            state <= SEND_ADDR;
            shift_reg <= addr[15:8]; // Load high byte of address
            bit_cnt <= 0;
          end
        end

        SEND_ADDR:
        begin

          spi_clk <= 0;
          if (bit_cnt < 8)
          begin
            spi_mosi <= shift_reg[7];
            shift_reg <= shift_reg << 1;
            spi_clk <= 0;
            last_state <= state;
            state <= TOGGLECLKON;
            bit_cnt <= bit_cnt + 1;
          end
          else if (byte_cnt == 0)
          begin
            shift_reg <= addr[7:0]; // Load low byte of addresscc
            byte_cnt <= 1;
            bit_cnt <= 0;
          end
          else
          begin
            state <= command ? WRITE_DATA : READ_DATA;
            shift_reg <= command ? data_in[15:8] : 8'h00; // Load high data or dummy
            recv_data[15:0] <= 16'h0000; // Clear received data
            bit_cnt <= 0;
            byte_cnt <= 0;
            spi_mosi <= 1'b0;
          end
        end

        WRITE_DATA:
        begin

          spi_clk <= 0;
          if (bit_cnt < 8)
          begin
            spi_mosi <= shift_reg[7];
            shift_reg <= shift_reg << 1;

            last_state <= state;
            state <= TOGGLECLKON;
            bit_cnt <= bit_cnt + 1;
          end
          else if (byte_cnt == 0)
          begin
            shift_reg <= data_in[7:0]; // Load low byte
            byte_cnt <= 1;
            bit_cnt <= 0;
          end
          else
          begin
            state <= decideFate; // Decide next state based on command
          end
        end

        READ_DATA:
        begin

          spi_clk <= 0;
          if (bit_cnt < 17)
          begin
            last_state<=state;

            if (bit_cnt<16)
              state <= TOGGLECLKON;
            bit_cnt <= bit_cnt + 1;
            recv_data[15:0] <= {recv_data[14:0], spi_miso}; // Shift left


          end
          else
          begin
            recv_data[15:0] <= {recv_data[14:0], spi_miso};
            data_out <= recv_data;
            state <= decideFate; // Decide next state based on command
            bit_cnt <= 0;
          end
        end


        STOP:
        begin

          spi_clk <= 0;
          spi_cs <= 1'b1;
          busy <= 1'b0;
          state <= IDLE;
        end

        TOGGLECLKON:
        begin
          spi_clk <= 1;
          state <= last_state;
        end

        decideFate:
        begin
          if (command == prev_command &&
              addr == prev_addr + 1 &&
              is_continous == prev_is_continous)
          begin
            // Continue without releasing CS
            shift_reg <= command ? data_in[15:8] : 8'h00;
            bit_cnt <= 0;
            byte_cnt <= 0;
            recv_data <= 0;
            spi_mosi <= 0;
            state <= command ? WRITE_DATA : READ_DATA;

            // Update previous address
            prev_addr <= addr;
          end
          else
          begin
            // End transaction
            state <= STOP;
          end
        end
        default :
          state <= STOP;

      endcase
    end

  end

endmodule

module cpu_cycle_controller
  (
    input  wire clk,
    input  wire rst_n,

    input  wire fetch_done,
    input  wire data_done,

    input  wire ld,
    input  wire st,

    output wire fetch_req,
    output wire execute_now_pulse
  );

  localparam S_REQ_FETCH  = 2'd0;
  localparam S_WAIT_FETCH = 2'd1;
  localparam S_EXECUTE    = 2'd2;
  localparam S_WAIT_DATA  = 2'd3;

  reg [1:0] state;

  wire execute_now;
  assign execute_now = (state == S_EXECUTE);
  assign fetch_req   = (state == S_REQ_FETCH);

  always @(posedge clk , negedge rst_n)
  begin
    if (!rst_n)
    begin
      state <= S_REQ_FETCH;
    end
    else
    begin
      case (state)
        S_REQ_FETCH:
          state <= S_WAIT_FETCH;

        S_WAIT_FETCH:
        begin
          if (fetch_done)
            state <= S_EXECUTE;
        end

        S_EXECUTE:
        begin
          if (ld || st)
            state <= S_WAIT_DATA;
          else
            state <= S_REQ_FETCH;
        end

        S_WAIT_DATA:
        begin
          if (data_done)
            state <= S_REQ_FETCH;
        end

        default:
          state <= S_REQ_FETCH;
      endcase
    end
  end

  // rise detector
  reg sig_d;
  always @(posedge clk, negedge rst_n)
  begin
    if (!rst_n)
      sig_d <= 1'b0;
    else
      sig_d <= execute_now;
  end

  assign execute_now_pulse = execute_now & ~sig_d;
endmodule

module interrupt_controller_small (
    input  [3:0] dOut,
    input  [15:0] Addr,
    input         ioW,
    input         ioR,
    input         C,
    input         rst_n,

    input  [3:0]  irq_in,
    input         imm,
    input         reti,
    input         pc_en,

    input  [15:0] CPUInterruptEnableAddr,
    input  [15:0] inputInterruptAddr,
    input  [15:0] interruptRegAddr,

    output [15:0] InterruptOut,
    output        intr,
    output        irq_lock
);

  reg       global_enable;
  reg       irq_lock_r   ;
  reg [3:0] irq_enable   ;
  reg [3:0] irq_pending  ;

  wire wr_ctrl;
  wire wr_enable;
  wire wr_pending;

  wire rd_ctrl;
  wire rd_enable;
  wire rd_pending;

  wire [3:0] pending_with_new_irq;
  wire [3:0] active_irq;
  wire       intr_take;

  assign wr_ctrl    = ioW && (Addr == CPUInterruptEnableAddr);
  assign wr_enable  = ioW && (Addr == inputInterruptAddr);
  assign wr_pending = ioW && (Addr == interruptRegAddr);

  assign rd_ctrl    = ioR && (Addr == CPUInterruptEnableAddr);
  assign rd_enable  = ioR && (Addr == inputInterruptAddr);
  assign rd_pending = ioR && (Addr == interruptRegAddr);

  assign pending_with_new_irq = irq_pending | irq_in;
  assign active_irq           = irq_pending & irq_enable;

  assign intr      = global_enable && !irq_lock_r && !imm && (active_irq != 4'b0000);
  assign irq_lock  = irq_lock_r;
  assign intr_take = intr && pc_en;

  always @(posedge C or negedge rst_n)
  begin
    if (!rst_n)
    begin
      global_enable <= 1'b0;
      irq_lock_r    <= 1'b0;
      irq_enable    <= 4'b0000;
      irq_pending   <= 4'b0000;
    end
    else
    begin
      // default: latch new interrupt requests
      irq_pending <= pending_with_new_irq;

      // global interrupt enable
      if (wr_ctrl)
        global_enable <= dOut[0];

      // source enable bits [3:0]
      if (wr_enable)
        irq_enable <= dOut[3:0];

      // write 1 to clear pending bits
      if (wr_pending)
        irq_pending <= pending_with_new_irq & ~dOut[3:0];

      // lock once interrupt is actually taken
      if (intr_take)
        irq_lock_r <= 1'b1;

      // unlock only on RETI
      if (reti)
        irq_lock_r <= 1'b0;
    end
  end

  assign InterruptOut =
      rd_ctrl    ? {13'h0000, intr, irq_lock_r, global_enable} :
      rd_enable  ? {12'h000, irq_enable} :
      rd_pending ? {12'h000, irq_pending} :
      16'h0000;

endmodule
module lfsr_RandomNumberGen (
    input  [15:0] adrrIn,
    input  [7:0] dataIn,
    input         ioW,
    input         clk,
    input         ioR,
    input  [15:0] SeedAdr,
    input  [15:0] RngAdr,
    output [15:0] Out
);

    reg [7:0] seed_reg;
    reg [7:0] lfsr    ;

    wire seed_wr  = ioW && (adrrIn == SeedAdr);
    wire seed_rd  = ioR && (adrrIn == SeedAdr);
    wire rng_rd   = ioR && (adrrIn == RngAdr);

    // 8-bit maximal-length taps
    // polynomial: x^8 + x^6 + x^5 + x^4 + 1
    wire feedback = lfsr[7] ^ lfsr[5] ^ lfsr[4] ^ lfsr[3];

    always @(posedge clk) begin
        if (seed_wr) begin
            seed_reg <= dataIn[7:0];
            lfsr <= (dataIn[7:0] == 8'h00) ? 8'h01 : dataIn[7:0];
        end else begin
            lfsr <= {lfsr[6:0], feedback};
        end
    end

    assign Out = seed_rd ? {8'h00, seed_reg} :
                 rng_rd  ? {8'h00, lfsr}     :
                           16'h0000;

endmodule
module timer (
    input  [15:0] dOut,
    input  [15:0] Addr,
    input         ioW,
    input         ioR,
    input         C,
    input         InterLock,
    input  [15:0] timerConfigAddr,
    input  [15:0] timerTargetAddr,
    input  [15:0] timerResetAddr,
    input  [15:0] timerReadAddr,
    input  [15:0] timerSyncStartAddr,
    input         rst_n,
    output [15:0] TimerOut,
    output        timer_interrupt
  );

  reg [15:0] target       ;
  reg [15:0] count        ;
  reg [14:0] prescale_cnt ;
  reg [6:0]  conf         ;

  wire wr_conf   = ioW && (Addr == timerConfigAddr);
  wire wr_target = ioW && (Addr == timerTargetAddr);
  wire wr_reset  = ioW && (Addr == timerResetAddr) && dOut[0];
  wire wr_sync_start = ioW && (Addr == timerSyncStartAddr);

  wire rd_count  = ioR && (Addr == timerReadAddr);
  wire rd_target = ioR && (Addr == timerTargetAddr);
  wire rd_conf   = ioR && (Addr == timerConfigAddr);

  wire       timer_en     = conf[0];
  wire [3:0] prescaler    = conf[4:1];
  wire       auto_reload  = conf[5];
  wire       irq_en       = conf[6];
  wire       target_valid = (target != 16'h0000);
  wire       matched      = target_valid && (count == target);

  reg tick;
  always @(*)
  begin
    case (prescaler)
      4'd0:
        tick = 1'b1;                  // /1
      4'd1:
        tick = prescale_cnt[0];       // /2
      4'd2:
        tick = &prescale_cnt[1:0];    // /4
      4'd3:
        tick = &prescale_cnt[2:0];    // /8
      4'd4:
        tick = &prescale_cnt[3:0];    // /16
      4'd5:
        tick = &prescale_cnt[4:0];    // /32
      4'd6:
        tick = &prescale_cnt[5:0];    // /64
      4'd7:
        tick = &prescale_cnt[6:0];    // /128
      4'd8:
        tick = &prescale_cnt[7:0];    // /256
      4'd9:
        tick = &prescale_cnt[8:0];    // /512
      4'd10:
        tick = &prescale_cnt[9:0];    // /1024
      4'd11:
        tick = &prescale_cnt[10:0];   // /2048
      4'd12:
        tick = &prescale_cnt[11:0];   // /4096
      4'd13:
        tick = &prescale_cnt[12:0];   // /8192
      4'd14:
        tick = &prescale_cnt[13:0];   // /16384
      4'd15:
        tick = &prescale_cnt[14:0];   // /32768
      default:
        tick = 1'b1;
    endcase
  end

  always @(posedge C or negedge rst_n)
  begin
    if (!rst_n)
    begin
      target       <= 16'h0000;
      count        <= 16'h0000;
      prescale_cnt <= 15'h0000;
      conf         <= 7'h00;
    end
    else
    begin
      if (wr_conf)
      begin
        conf         <= dOut[6:0];
        prescale_cnt <= 15'h0000;
      end

      if (wr_target)
        target <= dOut;

      if (wr_sync_start)
        conf[0] <= dOut[0];

      if (wr_reset)
      begin
        count        <= 16'h0000;
        prescale_cnt <= 15'h0000;
      end
      else
      begin
        if (timer_en)
          prescale_cnt <= prescale_cnt + 15'd1;

        if (timer_en && !InterLock)
        begin
          if (matched)
          begin
            if (auto_reload)
              count <= 16'h0000;
          end
          else if (tick)
          begin
            count <= count + 16'd1;
          end
        end
      end
    end
  end

  assign TimerOut = rd_count  ? count             :
         rd_target ? target            :
         rd_conf   ? {9'h000, conf}   :
         16'h0000;

  assign timer_interrupt = irq_en && !InterLock && matched;

endmodule

module timer_tiny (
    input  [8:0] dOut,
    input  [15:0] Addr,
    input         ioW,
    input         ioR,
    input         C,
    input         InterLock,
    input  [15:0] timerConfigAddr,
    input  [15:0] timerTargetAddr,
    input  [15:0] timerResetAddr,
    input  [15:0] timerReadAddr,
    input  [15:0] timerSyncStartAddr,
    input         rst_n,
    output [15:0] TimerOut,
    output        timer_interrupt
  );

  reg [8:0] target        ;
  reg [8:0] count         ;
  reg [14:0] prescale_cnt  ;
  reg [6:0]  conf         ;

  wire wr_conf   = ioW && (Addr == timerConfigAddr);
  wire wr_target = ioW && (Addr == timerTargetAddr);
  wire wr_reset  = ioW && (Addr == timerResetAddr) && dOut[0];
  wire wr_sync_start = ioW && (Addr == timerSyncStartAddr);

  wire rd_count  = ioR && (Addr == timerReadAddr);
  wire rd_target = ioR && (Addr == timerTargetAddr);
  wire rd_conf   = ioR && (Addr == timerConfigAddr);

  wire       timer_en     = conf[0];
  wire [3:0] prescaler    = conf[4:1];
  wire       auto_reload  = conf[5];
  wire       irq_en       = conf[6];
  wire       target_valid = (target != 16'h0000);
  wire       matched      = target_valid && (count == target);

  reg tick;
  always @(*)
  begin
    case (prescaler)
      4'd0:
        tick = 1'b1;                  // /1
      4'd1:
        tick = prescale_cnt[0];       // /2
      4'd2:
        tick = &prescale_cnt[1:0];    // /4
      4'd3:
        tick = &prescale_cnt[2:0];    // /8
      4'd4:
        tick = &prescale_cnt[3:0];    // /16
      4'd5:
        tick = &prescale_cnt[4:0];    // /32
      4'd6:
        tick = &prescale_cnt[5:0];    // /64
      4'd7:
        tick = &prescale_cnt[6:0];    // /128
      4'd8:
        tick = &prescale_cnt[7:0];    // /256
      4'd9:
        tick = &prescale_cnt[8:0];    // /512
      4'd10:
        tick = &prescale_cnt[9:0];    // /1024
      4'd11:
        tick = &prescale_cnt[10:0];   // /2048
      4'd12:
        tick = &prescale_cnt[11:0];   // /4096
      4'd13:
        tick = &prescale_cnt[12:0];   // /8192
      4'd14:
        tick = &prescale_cnt[13:0];   // /16384
      4'd15:
        tick = &prescale_cnt[14:0];   // /32768
      default:
        tick = 1'b1;
    endcase
  end

  always @(posedge C or negedge rst_n)
  begin
    if (!rst_n)
    begin
      target       <= 8'h00;
      count        <= 8'h00;
      prescale_cnt <= 15'h0000;
      conf         <= 7'h00;
    end
    else
    begin
      if (wr_conf)
      begin
        conf         <= dOut[6:0];
        prescale_cnt <= 15'h0000;
      end

      if (wr_target)
        target <= dOut[8:0];

      if (wr_sync_start)
        conf[0] <= dOut[0];

      if (wr_reset)
      begin
        count        <= 8'h00;
        prescale_cnt <= 15'h0000;
      end
      else
      begin
        if (timer_en)
          prescale_cnt <= prescale_cnt + 15'd1;

        if (timer_en && !InterLock)
        begin
          if (matched)
          begin
            if (auto_reload)
              count <= 8'h00;
          end
          else if (tick)
          begin
            count <= count + 8'd1;
          end
        end
      end
    end
  end

  assign TimerOut = rd_count  ? {8'h0, count }            :
         rd_target ? {8'h0, target }            :
         rd_conf   ? {9'h000, conf}   :
         16'h0000;

  assign timer_interrupt = irq_en && !InterLock && matched;

endmodule

module RegisterBlock (
    input  [15:0] DataIn,
    input         WE,
    input         clk,
    input  [3:0]  src,
    input  [3:0]  Dest,
    output [15:0] RDest,
    output [15:0] Rsrc
  );

  reg [15:0] regs [0:15];

  always @(negedge clk )
  begin

    if (WE)
    begin
      regs[Dest] <= DataIn;
    end
  end

  // read ports
  assign Rsrc  = regs[src];
  assign RDest = regs[Dest];

endmodule


module Mux_16x1_NBits #(
    parameter Bits = 2
)
(
    input [3:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    input [(Bits - 1):0] in_2,
    input [(Bits - 1):0] in_3,
    input [(Bits - 1):0] in_4,
    input [(Bits - 1):0] in_5,
    input [(Bits - 1):0] in_6,
    input [(Bits - 1):0] in_7,
    input [(Bits - 1):0] in_8,
    input [(Bits - 1):0] in_9,
    input [(Bits - 1):0] in_10,
    input [(Bits - 1):0] in_11,
    input [(Bits - 1):0] in_12,
    input [(Bits - 1):0] in_13,
    input [(Bits - 1):0] in_14,
    input [(Bits - 1):0] in_15,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            4'h0: out = in_0;
            4'h1: out = in_1;
            4'h2: out = in_2;
            4'h3: out = in_3;
            4'h4: out = in_4;
            4'h5: out = in_5;
            4'h6: out = in_6;
            4'h7: out = in_7;
            4'h8: out = in_8;
            4'h9: out = in_9;
            4'ha: out = in_10;
            4'hb: out = in_11;
            4'hc: out = in_12;
            4'hd: out = in_13;
            4'he: out = in_14;
            4'hf: out = in_15;
            default:
                out = 'h0;
        endcase
    end
endmodule

module i2c_master_ctrl (
    input              clk,
    input              rst_n,

    input              wr_en,
    input      [3:0]   reg_addr,
    input      [15:0]  cpu_din,
    output reg [15:0]  cpu_dout,

    input              sda_in,
    input              scl_in,
    output             sda_out,
    output             scl_out,
    output reg         sda_oe,
    output reg         scl_oe,

    output             interrupt
);

assign sda_out = 1'b0;
assign scl_out = 1'b0;
assign interrupt = irq_enable & irq_pending;

localparam ST_IDLE       = 4'd0;
localparam ST_START_1    = 4'd1;
localparam ST_START_2    = 4'd2;
localparam ST_START_3    = 4'd3;
localparam ST_BIT_SETUP  = 4'd4;
localparam ST_BIT_HIGH   = 4'd5;
localparam ST_BIT_LOW    = 4'd6;
localparam ST_ACK_SETUPW = 4'd7;
localparam ST_ACK_HIGHW  = 4'd8;
localparam ST_ACK_LOWW   = 4'd9;
localparam ST_ACK_SETUPR = 4'd10;
localparam ST_ACK_HIGHR  = 4'd11;
localparam ST_ACK_LOWR   = 4'd12;
localparam ST_STOP_1     = 4'd13;
localparam ST_STOP_2     = 4'd14;
localparam ST_STOP_3     = 4'd15;

reg        enable;
reg        irq_enable;
reg        stretch_enable;

reg        op_busy;
reg        bus_active;
reg        done;
reg        ack_error;
reg        rx_valid;
reg        irq_pending;

reg [15:0] prescale_reg;
reg [15:0] divcnt;
reg        sm_tick;

reg [7:0]  tx_data_reg;
reg [7:0]  rx_data_reg;

reg [7:0]  tx_shift;
reg [7:0]  rx_shift;
reg [3:0]  bit_count;

reg        cmd_start;
reg        cmd_stop;
reg        cmd_write;
reg        cmd_read;
reg        cmd_read_nack;

reg [3:0]  state;

wire launch_cmd;
assign launch_cmd = wr_en && (reg_addr == 4'h4) && !op_busy && enable &&
                    (cpu_din[0] || cpu_din[1] || cpu_din[2] || cpu_din[3]);

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        enable         <= 1'b0;
        irq_enable     <= 1'b0;
        stretch_enable <= 1'b0;

        op_busy        <= 1'b0;
        bus_active     <= 1'b0;
        done           <= 1'b0;
        ack_error      <= 1'b0;
        rx_valid       <= 1'b0;
        irq_pending    <= 1'b0;

        prescale_reg   <= 16'd0;
        divcnt         <= 16'd0;
        sm_tick        <= 1'b0;

        tx_data_reg    <= 8'd0;
        rx_data_reg    <= 8'd0;
        tx_shift       <= 8'd0;
        rx_shift       <= 8'd0;
        bit_count      <= 4'd0;

        cmd_start      <= 1'b0;
        cmd_stop       <= 1'b0;
        cmd_write      <= 1'b0;
        cmd_read       <= 1'b0;
        cmd_read_nack  <= 1'b0;

        state          <= ST_IDLE;

        sda_oe         <= 1'b0;
        scl_oe         <= 1'b0;
    end else begin
        sm_tick <= 1'b0;

        if (op_busy) begin
            if (prescale_reg == 16'd0) begin
                sm_tick <= 1'b1;
            end else begin
                if (divcnt == 16'd0) begin
                    divcnt  <= prescale_reg;
                    sm_tick <= 1'b1;
                end else begin
                    divcnt <= divcnt - 16'd1;
                end
            end
        end else begin
            divcnt <= 16'd0;
        end

        if (wr_en) begin
            case (reg_addr)
                4'h0: begin
                    enable         <= cpu_din[0];
                    irq_enable     <= cpu_din[1];
                    stretch_enable <= cpu_din[2];
                end

                4'h1: begin
                    if (cpu_din[2]) done        <= 1'b0;
                    if (cpu_din[3]) ack_error   <= 1'b0;
                    if (cpu_din[4]) rx_valid    <= 1'b0;
                    if (cpu_din[5]) irq_pending <= 1'b0;
                end

                4'h2: begin
                    prescale_reg <= cpu_din;
                end

                4'h3: begin
                    tx_data_reg <= cpu_din[7:0];
                end
            endcase
        end

        if (launch_cmd) begin
            cmd_start     <= cpu_din[0];
            cmd_stop      <= cpu_din[1];
            cmd_write     <= cpu_din[2];
            cmd_read      <= cpu_din[3];
            cmd_read_nack <= cpu_din[4];

            done        <= 1'b0;
            ack_error   <= 1'b0;
            irq_pending <= 1'b0;

            tx_shift    <= tx_data_reg;
            rx_shift    <= 8'd0;
            bit_count   <= 4'd7;
            op_busy     <= 1'b1;

            if (cpu_din[0]) begin
                state  <= ST_START_1;
                sda_oe <= 1'b0;
                scl_oe <= 1'b0;
            end else if (cpu_din[2] || cpu_din[3]) begin
                state <= ST_BIT_SETUP;
                scl_oe <= 1'b1;
            end else if (cpu_din[1]) begin
                state  <= ST_STOP_1;
                sda_oe <= 1'b1;
                scl_oe <= 1'b1;
            end else begin
                op_busy <= 1'b0;
                done    <= 1'b1;
                irq_pending <= 1'b1;
                state   <= ST_IDLE;
            end
        end

        if (sm_tick && op_busy) begin
            case (state)
                ST_IDLE: begin
                    op_busy <= 1'b0;
                end

                ST_START_1: begin
                    sda_oe <= 1'b0;
                    scl_oe <= 1'b0;
                    if (sda_in && ((!stretch_enable) || scl_in)) begin
                        state <= ST_START_2;
                    end
                end

                ST_START_2: begin
                    sda_oe <= 1'b1; // SDA low while SCL high
                    scl_oe <= 1'b0;
                    state  <= ST_START_3;
                end

                ST_START_3: begin
                    scl_oe     <= 1'b1; // pull SCL low
                    bus_active <= 1'b1;

                    if (cmd_write || cmd_read) begin
                        state <= ST_BIT_SETUP;
                    end else if (cmd_stop) begin
                        state <= ST_STOP_1;
                    end else begin
                        done        <= 1'b1;
                        irq_pending <= 1'b1;
                        op_busy     <= 1'b0;
                        state       <= ST_IDLE;
                    end
                end

                ST_BIT_SETUP: begin
                    scl_oe <= 1'b1; // keep clock low during setup

                    if (cmd_write) begin
                        if (tx_shift[bit_count])
                            sda_oe <= 1'b0; // release for logic 1
                        else
                            sda_oe <= 1'b1; // drive low for logic 0
                    end else begin
                        sda_oe <= 1'b0; // read bit: release SDA
                    end

                    state <= ST_BIT_HIGH;
                end

                ST_BIT_HIGH: begin
                    scl_oe <= 1'b0; // release SCL high

                    if ((!stretch_enable) || scl_in) begin
                        if (cmd_read)
                            rx_shift[bit_count] <= sda_in;

                        state <= ST_BIT_LOW;
                    end
                end

                ST_BIT_LOW: begin
                    scl_oe <= 1'b1; // drive SCL low again

                    if (bit_count != 4'd0) begin
                        bit_count <= bit_count - 4'd1;
                        state     <= ST_BIT_SETUP;
                    end else begin
                        if (cmd_write)
                            state <= ST_ACK_SETUPW;
                        else
                            state <= ST_ACK_SETUPR;
                    end
                end

                ST_ACK_SETUPW: begin
                    sda_oe <= 1'b0; // slave drives ACK/NACK
                    scl_oe <= 1'b1;
                    state  <= ST_ACK_HIGHW;
                end

                ST_ACK_HIGHW: begin
                    scl_oe <= 1'b0;

                    if ((!stretch_enable) || scl_in) begin
                        if (sda_in)
                            ack_error <= 1'b1;

                        state <= ST_ACK_LOWW;
                    end
                end

                ST_ACK_LOWW: begin
                    scl_oe <= 1'b1;
                    sda_oe <= 1'b0;

                    if (cmd_stop) begin
                        state <= ST_STOP_1;
                    end else begin
                        done        <= 1'b1;
                        irq_pending <= 1'b1;
                        op_busy     <= 1'b0;
                        state       <= ST_IDLE;
                    end
                end

                ST_ACK_SETUPR: begin
                    scl_oe <= 1'b1;

                    if (cmd_read_nack)
                        sda_oe <= 1'b0; // NACK = release high
                    else
                        sda_oe <= 1'b1; // ACK = drive low

                    state <= ST_ACK_HIGHR;
                end

                ST_ACK_HIGHR: begin
                    scl_oe <= 1'b0;

                    if ((!stretch_enable) || scl_in) begin
                        state <= ST_ACK_LOWR;
                    end
                end

                ST_ACK_LOWR: begin
                    scl_oe      <= 1'b1;
                    sda_oe      <= 1'b0;
                    rx_data_reg <= rx_shift;
                    rx_valid    <= 1'b1;

                    if (cmd_stop) begin
                        state <= ST_STOP_1;
                    end else begin
                        done        <= 1'b1;
                        irq_pending <= 1'b1;
                        op_busy     <= 1'b0;
                        state       <= ST_IDLE;
                    end
                end

                ST_STOP_1: begin
                    sda_oe <= 1'b1; // SDA low
                    scl_oe <= 1'b1; // SCL low
                    state  <= ST_STOP_2;
                end

                ST_STOP_2: begin
                    sda_oe <= 1'b1; // keep SDA low
                    scl_oe <= 1'b0; // release SCL high

                    if ((!stretch_enable) || scl_in) begin
                        state <= ST_STOP_3;
                    end
                end

                ST_STOP_3: begin
                    sda_oe      <= 1'b0; // release SDA high
                    scl_oe      <= 1'b0;
                    bus_active  <= 1'b0;
                    done        <= 1'b1;
                    irq_pending <= 1'b1;
                    op_busy     <= 1'b0;
                    state       <= ST_IDLE;
                end

                default: begin
                    sda_oe      <= 1'b0;
                    scl_oe      <= 1'b0;
                    bus_active  <= 1'b0;
                    done        <= 1'b1;
                    ack_error   <= 1'b1;
                    irq_pending <= 1'b1;
                    op_busy     <= 1'b0;
                    state       <= ST_IDLE;
                end
            endcase
        end
    end
end

always @(*) begin
    cpu_dout = 16'd0;

    case (reg_addr)
        4'h0: begin
            cpu_dout[0] = enable;
            cpu_dout[1] = irq_enable;
            cpu_dout[2] = stretch_enable;
        end

        4'h1: begin
            cpu_dout[0] = op_busy;
            cpu_dout[1] = bus_active;
            cpu_dout[2] = done;
            cpu_dout[3] = ack_error;
            cpu_dout[4] = rx_valid;
            cpu_dout[5] = irq_pending;
        end

        4'h2: begin
            cpu_dout = prescale_reg;
        end

        4'h3: begin
            cpu_dout[7:0] = rx_data_reg;
        end

        4'h4: begin
            cpu_dout[0] = cmd_start;
            cpu_dout[1] = cmd_stop;
            cpu_dout[2] = cmd_write;
            cpu_dout[3] = cmd_read;
            cpu_dout[4] = cmd_read_nack;
        end

        default: begin
            cpu_dout = 16'd0;
        end
    endcase
end

endmodule
module is_different (
    input  [15:0] in1,
    input  [15:0] in2,

    output        different
  );
  assign different = (in1 != in2);

endmodule


module singExtend (
  input [7:0] inst,
  output [15:0] \4S , // The four bits taken from Rs.
  output [15:0] \8SD , // The eight bits taken from Rs,Rd with sign extension.
  output [15:0] \4D  // The four bits taken from Rd.

);
  wire s0;
  assign \4D [3:0] = inst[7:4];
  assign \4D [15:4] = 12'b0;
  assign \4S [3:0] = inst[3:0];
  assign \4S [15:4] = 12'b0;
  assign s0 = inst[7];
  assign \8SD [6:0] = inst[6:0];
  assign \8SD [7] = s0;
  assign \8SD [8] = s0;
  assign \8SD [9] = s0;
  assign \8SD [10] = s0;
  assign \8SD [11] = s0;
  assign \8SD [12] = s0;
  assign \8SD [13] = s0;
  assign \8SD [14] = s0;
  assign \8SD [15] = s0;
endmodule
module opcode_microcode_rom(
    input  [6:0] opcode,
    output muxb0,
    output muxb1,
    output muxb2,
    output aluop0,
    output aluop1,
    output aluop2,
    output aluop3,
    output aluop4,
    output aluop5,
    output WE,
    output sf,
    output iem0,
    output iem1,
    output br0,
    output br1,
    output br2,
    output muxA,
    output ld,
    output st,
    output abs,
    output ioW,
    output ioR,
    output stPC,
    output Reti
);

reg [23:0] ctrl;

assign {
    muxb0,
    muxb1,
    muxb2,
    aluop0,
    aluop1,
    aluop2,
    aluop3,
    aluop4,
    aluop5,
    WE,
    sf,
    iem0,
    iem1,
    br0,
    br1,
    br2,
    muxA,
    ld,
    st,
    abs,
    ioW,
    ioR,
    stPC,
    Reti
} = ctrl;

always @(*) begin
    case (opcode)
        7'b0000000: ctrl = 24'b0000_0000_0000_0000_0000_0000;//8'hx00:
        7'b0000001: ctrl = 24'b0000_0000_0100_0000_1000_0000;//8'hx01:
        7'b0000010: ctrl = 24'b0000_0000_1110_0000_0000_0000;//8'hx02:
        7'b0000011: ctrl = 24'b0001_0000_1110_0000_0000_0000;//8'hx03:
        7'b0000100: ctrl = 24'b0000_0001_0110_0000_0000_0000;//8'hx04:
        7'b0000101: ctrl = 24'b0001_0001_0110_0000_0000_0000;//8'hx05:
        7'b0000110: ctrl = 24'b0000_0001_1110_0000_0000_0000;//8'hx06:
        7'b0000111: ctrl = 24'b0000_0010_0110_0000_0000_0000;//8'hx07:
        7'b0001000: ctrl = 24'b0000_0010_1110_0000_0000_0000;//8'hx08:
        7'b0001001: ctrl = 24'b0100_0000_0101_0000_0000_0000;//8'hx09:
        7'b0001010: ctrl = 24'b1010_0000_0100_0000_0000_0000;//8'hx0A:
        7'b0001011: ctrl = 24'b0100_0000_1111_0000_0000_0000;//8'hx0B:
        7'b0001100: ctrl = 24'b1010_0000_1110_0000_0000_0000;//8'hx0C:
        7'b0001101: ctrl = 24'b0101_0000_1111_0000_0000_0000;//8'hx0D:
        7'b0001110: ctrl = 24'b1011_0000_1110_0000_0000_0000;//8'hx0E:
        7'b0001111: ctrl = 24'b0100_0001_0111_0000_0000_0000;//8'hx0F:
        7'b0010000: ctrl = 24'b1010_0001_0110_0000_0000_0000;//8'hx10:
        7'b0010001: ctrl = 24'b0101_0001_0111_0000_0000_0000;//8'hx11:
        7'b0010010: ctrl = 24'b1011_0001_0110_0000_0000_0000;//8'hx12:
        7'b0010011: ctrl = 24'b0000_0011_1100_0000_0000_0000;//8'hx13:
        7'b0010100: ctrl = 24'b0100_0001_1111_0000_0000_0000;//8'hx14:
        7'b0010101: ctrl = 24'b1010_0001_1110_0000_0000_0000;//8'hx15:
        7'b0010110: ctrl = 24'b0100_0010_0111_0000_0000_0000;//8'hx16:
        7'b0010111: ctrl = 24'b1010_0010_0110_0000_0000_0000;//8'hx17:
        7'b0011000: ctrl = 24'b0100_0010_1111_0000_0000_0000;//8'hx18:
        7'b0011001: ctrl = 24'b1010_0010_1110_0000_0000_0000;//8'hx19:
        7'b0011010: ctrl = 24'b0000_0011_0100_0000_0000_0000;//8'hx1A:
        //17'b0011011:ctrl =28'b0000_0110_1110_0000_0000_0000;//8'hx1B:
        //17'b0011100:ctrl =28'b0100_0110_1111_0000_0000_0000;//8'hx1C:
        //17'b0011101:ctrl =28'b1010_0110_1110_0000_0000_0000;//8'hx1D:
        7'b0011110: ctrl = 24'b0000_0001_0010_0000_0000_0000;//8'hx1E:
        7'b0011111: ctrl = 24'b0001_0001_0010_0000_0000_0000;//8'hx1F:
        7'b0100000: ctrl = 24'b0100_0001_0011_0000_0000_0000;//8'hx20:
        7'b0100001: ctrl = 24'b1010_0001_0010_0000_0000_0000;//8'hx21:
        7'b0100010: ctrl = 24'b0101_0001_0011_0000_0000_0000;//8'hx22:
        7'b0100011: ctrl = 24'b1011_0001_0010_0000_0000_0000;//8'hx23:
        7'b0100100: ctrl = 24'b0000_0100_0110_0000_0000_0000;//8'hx24:
        7'b0100101: ctrl = 24'b0000_0100_1110_0000_0000_0000;//8'hx25:
        7'b0100110: ctrl = 24'b0001_0100_0110_0000_0000_0000;//8'hx26:
        7'b0100111: ctrl = 24'b0001_0100_1110_0000_0000_0000;//8'hx27:
        7'b0101000: ctrl = 24'b0000_0101_0110_0000_0000_0000;//8'hx28:
        7'b0101001: ctrl = 24'b0000_0101_1100_0000_0000_0000;//8'hx29:
        7'b0101010: ctrl = 24'b0000_0110_0100_0000_0000_0000;//8'hx2A:
        7'b0101011: ctrl = 24'b0110_0000_1000_0000_0010_0000;//8'hx2B:
        7'b0101100: ctrl = 24'b0110_0000_1100_0000_1100_0000;//8'hx2C:
        7'b0101101: ctrl = 24'b0100_0000_0001_1000_0010_0000;//8'hx2D:
        7'b0101110: ctrl = 24'b1110_0000_0000_0000_0010_0000;//8'hx2E:
        7'b0101111: ctrl = 24'b0100_0000_0101_0000_0100_0000;//8'hx2F:
        7'b0110000: ctrl = 24'b1010_0000_0100_0000_0100_0000;//8'hx30:
        7'b0110001: ctrl = 24'b0100_0000_1000_0000_0010_0000;//8'hx31:
        7'b0110010: ctrl = 24'b0100_0000_1100_0000_1100_0000;//8'hx32:
        7'b0110011: ctrl = 24'b0010_0000_0100_0000_0000_0000;//8'hx33:
        7'b0110100: ctrl = 24'b1100_0000_0000_0001_0000_0000;//8'hx34:
        7'b0110101: ctrl = 24'b1100_0000_0000_0010_0000_0000;//8'hx35:
        7'b0110110: ctrl = 24'b1100_0000_0000_0011_0000_0000;//8'hx36:
        7'b0110111: ctrl = 24'b1100_0000_0000_0101_0000_0000;//8'hx37:
        7'b0111000: ctrl = 24'b1100_0000_0000_0110_0000_0000;//8'hx38:
        7'b0111001: ctrl = 24'b1100_0000_0000_0111_0000_0000;//8'hx39:
        7'b0111010: ctrl = 24'b0100_0000_0101_0000_0001_0010;//8'hx3A:
        7'b0111011: ctrl = 24'b0000_0000_0000_0000_0001_0000;//8'hx3B:
        7'b0111100: ctrl = 24'b0100_0000_0001_0000_0001_0000;//8'hx3C:
        7'b0111101: ctrl = 24'b1100_0000_0000_0100_0000_0000;//8'hx3D:
        7'b0111110: ctrl = 24'b0100_0000_0001_1000_0000_1000;//8'hx3E:
        7'b0111111: ctrl = 24'b1110_0000_0000_0000_0000_1000;//8'hx3F:
        7'b1000000: ctrl = 24'b0110_0000_1000_0000_0000_1000;//8'hx40:
        7'b1000001: ctrl = 24'b0100_0000_0101_0000_1000_0100;//8'hx41:
        7'b1000010: ctrl = 24'b1010_0000_0100_0000_1000_0100;//8'hx42:
        7'b1000011: ctrl = 24'b0110_0000_1100_0000_1000_0100;//8'hx43:
        7'b1000100: ctrl = 24'b0000_0000_0000_0000_0001_0001;//8'hx44:

        default:    ctrl = 24'b0000_0000_0000_0000_0000_0000;
    endcase
end

endmodule

module Mux_8x1_NBits #(
    parameter Bits = 2
)
(
    input [2:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    input [(Bits - 1):0] in_2,
    input [(Bits - 1):0] in_3,
    input [(Bits - 1):0] in_4,
    input [(Bits - 1):0] in_5,
    input [(Bits - 1):0] in_6,
    input [(Bits - 1):0] in_7,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            3'h0: out = in_0;
            3'h1: out = in_1;
            3'h2: out = in_2;
            3'h3: out = in_3;
            3'h4: out = in_4;
            3'h5: out = in_5;
            3'h6: out = in_6;
            3'h7: out = in_7;
            default:
                out = 'h0;
        endcase
    end
endmodule

module muxEncoder
  (
    input a,
    input b,
    input c,
    input d,
    output reg [1:0]Q
  );

  always @ (a,b,c,d)
  begin

    Q[0] = | d | b ;
    Q[1] = | d | c ;

  end
endmodule


module DIG_Neg #(
    parameter Bits = 1
)
(
      input signed [(Bits-1):0] in,
      output signed [(Bits-1):0] out
);
    assign out = -in;
endmodule

module DIG_Add
#(
    parameter Bits = 1
)
(
    input [(Bits-1):0] a,
    input [(Bits-1):0] b,
    input c_i,
    output [(Bits - 1):0] s,
    output c_o
);
   wire [Bits:0] temp;

   assign temp = a + b + c_i;
   assign s = temp [(Bits-1):0];
   assign c_o = temp[Bits];
endmodule



module DIG_Sub #(
    parameter Bits = 2
)
(
    input [(Bits-1):0] a,
    input [(Bits-1):0] b,
    input c_i,
    output [(Bits-1):0] s,
    output c_o
);
    wire [Bits:0] temp;

    assign temp = a - b - c_i;
    assign s = temp[(Bits-1):0];
    assign c_o = temp[Bits];
endmodule


module Mux_16x1
(
    input [3:0] sel,
    input in_0,
    input in_1,
    input in_2,
    input in_3,
    input in_4,
    input in_5,
    input in_6,
    input in_7,
    input in_8,
    input in_9,
    input in_10,
    input in_11,
    input in_12,
    input in_13,
    input in_14,
    input in_15,
    output reg out
);
    always @ (*) begin
        case (sel)
            4'h0: out = in_0;
            4'h1: out = in_1;
            4'h2: out = in_2;
            4'h3: out = in_3;
            4'h4: out = in_4;
            4'h5: out = in_5;
            4'h6: out = in_6;
            4'h7: out = in_7;
            4'h8: out = in_8;
            4'h9: out = in_9;
            4'ha: out = in_10;
            4'hb: out = in_11;
            4'hc: out = in_12;
            4'hd: out = in_13;
            4'he: out = in_14;
            4'hf: out = in_15;
            default:
                out = 'h0;
        endcase
    end
endmodule

module or_signal
  (
    input [15:0]D,
    output O
  );

 

  assign O = ~|D;


endmodule

module Alu (
  input [15:0] A,
  input [15:0] B,
  input carryIn,
  input [5:0] AluOp,
  output [15:0] Out,
  output Neg,
  output Zero,
  output CarryOut
);
  wire [3:0] s0;
  wire [15:0] s1;
  wire [15:0] s2;
  wire [15:0] s3;
  wire [15:0] s4;
  wire [15:0] s5;
  wire [15:0] s6;
  wire [15:0] s7;
  wire [15:0] s8;
  wire [15:0] s9;
  wire [15:0] s10;
  wire [15:0] s11;
  wire [15:0] s12;
  wire [15:0] Out_temp;
  wire [3:0] s13;
  wire s14;
  wire s15;
  wire s16;
  wire s17;
  wire s18;
  wire [4:0] sel;
  wire s19;
  wire s20;
  assign s3 = (A & B);
  assign s4 = (A | B);
  assign s5 = (A ^ B);
  assign s19 = (AluOp[5] & carryIn);
  assign s6 = ~ A;
  DIG_Neg #(
    .Bits(16)
  )
  DIG_Neg_i0 (
    .in( A ),
    .out( s7 )
  );
  assign s12[3:0] = A[7:4];
  assign s12[7:4] = A[3:0];
  assign s12[11:8] = A[15:12];
  assign s12[15:12] = A[11:8];
  assign s11[7:0] = A[15:8];
  assign s11[15:8] = A[7:0];
  assign sel = AluOp[4:0];
  assign s18 = A[0];
  assign s20 = A[15];
  assign s17 = A[0];
  assign s16 = A[15];
  DIG_Add #(
    .Bits(16)
  )
  DIG_Add_i1 (
    .a( A ),
    .b( B ),
    .c_i( s19 ),
    .s( s1 ),
    .c_o( s14 )
  );
  DIG_Sub #(
    .Bits(16)
  )
  DIG_Sub_i2 (
    .a( A ),
    .b( B ),
    .c_i( s19 ),
    .s( s2 ),
    .c_o( s15 )
  );
  assign s10[13:0] = A[14:1];
  assign s10[14] = s20;
  assign s10[15] = s20;
  assign s9[14:0] = A[15:1];
  assign s9[15] = s19;
  assign s8[0] = s19;
  assign s8[15:1] = A[14:0];
  assign s13 = sel[3:0];
  assign s0 = sel[3:0];
  Mux_16x1_NBits #(
    .Bits(16)
  )
  Mux_16x1_NBits_i3 (
    .sel( s0 ),
    .in_0( B ),
    .in_1( s1 ),
    .in_2( s2 ),
    .in_3( s3 ),
    .in_4( s4 ),
    .in_5( s5 ),
    .in_6( s6 ),
    .in_7( s7 ),
    .in_8( s8 ),
    .in_9( s9 ),
    .in_10( s10 ),
    .in_11( s11 ),
    .in_12( s12 ),
    .in_13( A ),
    .in_14( 16'b0 ),
    .in_15( 16'b0 ),
    .out( Out_temp )
  );
  Mux_16x1 Mux_16x1_i4 (
    .sel( s13 ),
    .in_0( 1'b0 ),
    .in_1( s14 ),
    .in_2( s15 ),
    .in_3( 1'b0 ),
    .in_4( 1'b0 ),
    .in_5( 1'b0 ),
    .in_6( 1'b0 ),
    .in_7( 1'b0 ),
    .in_8( s16 ),
    .in_9( s17 ),
    .in_10( s18 ),
    .in_11( 1'b0 ),
    .in_12( 1'b0 ),
    .in_13( 1'b0 ),
    .in_14( 1'b0 ),
    .in_15( 1'b0 ),
    .out( CarryOut )
  );
  // or_signal
  or_signal or_signal_i5 (
    .D( Out_temp ),
    .O( Zero )
  );
  assign Neg = Out_temp[15];
  assign Out = Out_temp;
endmodule

module Mux_4x1_NBits #(
    parameter Bits = 2
)
(
    input [1:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    input [(Bits - 1):0] in_2,
    input [(Bits - 1):0] in_3,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            2'h0: out = in_0;
            2'h1: out = in_1;
            2'h2: out = in_2;
            2'h3: out = in_3;
            default:
                out = 'h0;
        endcase
    end
endmodule


module CompSigned #(
    parameter Bits = 1
)
(
    input [(Bits -1):0] a,
    input [(Bits -1):0] b,
    output \> ,
    output \= ,
    output \<
);
    assign \> = $signed(a) > $signed(b);
    assign \= = $signed(a) == $signed(b);
    assign \< = $signed(a) < $signed(b);
endmodule


module tt_um_newDesign (
  input [7:0] ui_in,
  input clk,
  input [7:0] uio_in,
  input ena,
  input rst_n,
  output [7:0] uo_out,
  output [7:0] uio_out,
  output [7:0] uio_oe
);
  wire muxA;
  wire [15:0] s0;
  wire [15:0] s1;
  wire [15:0] s2;
  wire [2:0] muxB;
  wire [15:0] ImmReg;
  wire [15:0] s3;
  wire [15:0] s4;
  wire [15:0] s5;
  wire [15:0] s6;
  wire [15:0] s7;
  wire [3:0] s8;
  wire [3:0] s9;
  wire [7:0] OPcode;
  wire [1:0] s10;
  wire [15:0] s11;
  wire [15:0] mem_out;
  wire [15:0] iow_Din;
  wire [15:0] s12;
  wire [15:0] s13;
  wire [1:0] s14;
  wire s15;
  wire s16;
  wire s17;
  wire s18;
  wire [2:0] br;
  wire [7:0] s19;
  wire imm;
  wire [1:0] iem;
  wire s20;
  wire [15:0] inputReg;
  wire [6:0] s21;
  wire [6:0] s22;
  wire s23;
  wire s24;
  wire s25;
  wire s26;
  wire s27;
  wire s28;
  wire s29;
  wire s30;
  wire s31;
  wire [5:0] aluOp;
  wire s32;
  wire s33;
  wire s34;
  wire s35;
  wire s36;
  wire intr;
  wire \execute-pulse ;
  wire s37;
  wire Reti;
  wire s38;
  wire s39;
  wire s40;
  wire s41;
  wire [7:0] s42;
  wire [7:0] uo_out_temp;
  wire s43;
  wire sf;
  wire s44;
  wire s45;
  wire pc_en;
  wire s46;
  wire s47;
  wire [15:0] programAddr;
  wire [15:0] s48;
  wire s49;
  wire [15:0] s50;
  wire InterLock;
  wire ld;
  wire s51;
  wire stPC;
  wire [15:0] outR;
  wire fetch_request_pulse;
  wire s52;
  wire s53;
  wire [15:0] spi_data;
  wire spi_busy_ram;
  wire Fetch_done;
  wire data_done;
  wire s54;
  wire spi_st;
  wire spi_ld;
  wire [15:0] spi_addr;
  wire [15:0] spi_data_out;
  wire spi_target;
  wire spi_miso;
  wire spi_cs;
  wire spi_clock_ram;
  wire spi_mosi_ram;
  wire st;
  wire s55;
  wire WE;
  wire s56;
  wire s57;
  wire s58;
  wire abs;
  wire \sda-in ;
  wire \scl-in ;
  wire s59;
  wire s60;
  wire s61;
  wire s62;
  wire s63;
  wire spics_ram;
  wire spics_flash;
  wire sda_o;
  wire scl_o;
  wire sda_oe;
  wire scl_oe;
  wire [3:0] s64;
  wire [3:0] s65;
  wire [15:0] intr_reg;
  wire s66;
  wire s67;
  wire i2c_inter;
  wire [7:0] s68;
  wire [15:0] rngdat0;
  wire [15:0] timerdat1;
  wire [8:0] s69;
  wire [15:0] timerdat2;
  wire [3:0] s70;
  wire [15:0] i2cDat;
  wire [3:0] s71;
  wire s72;
  assign inputReg[0] = ui_in[0];
  assign inputReg[1] = ui_in[1];
  assign inputReg[2] = ui_in[2];
  assign inputReg[3] = ui_in[3];
  assign inputReg[4] = ui_in[4];
  assign inputReg[5] = ui_in[5];
  assign inputReg[6] = ui_in[6];
  assign inputReg[7] = ui_in[7];
  assign inputReg[15:8] = 8'b0;
  Mux_2x1 Mux_2x1_i0 (
    .sel( ena ),
    .in_0( 1'b1 ),
    .in_1( clk ),
    .out( s20 )
  );
  assign spi_miso = uio_in[0];
  assign \sda-in  = uio_in[1];
  assign \scl-in  = uio_in[2];
  assign s59 = uio_in[3];
  assign s60 = uio_in[4];
  assign s61 = uio_in[5];
  assign s62 = uio_in[6];
  assign s63 = uio_in[7];
  ImReg ImReg_i1 (
    .en( imm ),
    .iem( iem ),
    .C( s20 ),
    .inst( s7 ),
    .imm( ImmReg )
  );
  // NegR
  register_1bit register_1bit_i2 (
    .D( s43 ),
    .C( s20 ),
    .en( sf ),
    .rst( rst_n ),
    .Q( s17 )
  );
  // ZeroR
  register_1bit register_1bit_i3 (
    .D( s44 ),
    .C( s20 ),
    .en( sf ),
    .rst( rst_n ),
    .Q( s16 )
  );
  // CarryR
  register_1bit register_1bit_i4 (
    .D( s45 ),
    .C( s20 ),
    .en( sf ),
    .rst( rst_n ),
    .Q( s15 )
  );
  // outputReg
  register_8bit register_8bit_i5 (
    .D( s42 ),
    .C( s20 ),
    .en( s41 ),
    .rst( rst_n ),
    .Q( uo_out_temp )
  );
  // programCounter
  programCounter programCounter_i6 (
    .AluIn( s11 ),
    .clk( s20 ),
    .rst_n( rst_n ),
    .pc_en( pc_en ),
    .absJmp( s46 ),
    .intr( s37 ),
    .reti( s38 ),
    .relJmp( s47 ),
    .Nextpc( s12 ),
    .PC( programAddr )
  );
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i7 (
    .D( s48 ),
    .C( s20 ),
    .en( s49 ),
    .Q( s50 )
  );
  Mux_2x1_NBits #(
    .Bits(16)
  )
  Mux_2x1_NBits_i8 (
    .sel( InterLock ),
    .in_0( inputReg ),
    .in_1( s50 ),
    .out( s48 )
  );
  // memory_wait_controller
  memory_wait_controller memory_wait_controller_i9 (
    .clk( s20 ),
    .rst_n( rst_n ),
    .fetch_req( fetch_request_pulse ),
    .ld_req( s52 ),
    .st_req( s53 ),
    .fetch_addr( programAddr ),
    .data_addr( s11 ),
    .store_data( s1 ),
    .spi_data_out( spi_data ),
    .spi_busy( spi_busy_ram ),
    .mem_rdata( mem_out ),
    .fetch_done( Fetch_done ),
    .data_done( data_done ),
    .mem_stall( s54 ),
    .spi_st( spi_st ),
    .spi_ld( spi_ld ),
    .spi_addr( spi_addr ),
    .spi_data_in( spi_data_out ),
    .spi_target( spi_target )
  );
  // spi_memory_interface
  spi_memory_interface spi_memory_interface_i10 (
    .clk( s20 ),
    .spi_rst_n( rst_n ),
    .st( spi_st ),
    .ld( spi_ld ),
    .addr( spi_addr ),
    .data_in( spi_data_out ),
    .is_continous( 1'b0 ),
    .spi_miso( spi_miso ),
    .data_out( spi_data ),
    .spi_cs( spi_cs ),
    .spi_clk( spi_clock_ram ),
    .busy( spi_busy_ram ),
    .spi_mosi( spi_mosi_ram )
  );
  // cpu_cycle_controller
  cpu_cycle_controller cpu_cycle_controller_i11 (
    .clk( s20 ),
    .rst_n( rst_n ),
    .fetch_done( Fetch_done ),
    .data_done( data_done ),
    .ld( ld ),
    .st( st ),
    .fetch_req( fetch_request_pulse ),
    .execute_now_pulse( \execute-pulse  )
  );
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i12 (
    .D( mem_out ),
    .C( s20 ),
    .en( Fetch_done ),
    .Q( s7 )
  );
  // interrupt_controller_small
  interrupt_controller_small interrupt_controller_small_i13 (
    .dOut( s64 ),
    .Addr( s11 ),
    .ioW( s40 ),
    .ioR( s51 ),
    .C( s20 ),
    .rst_n( rst_n ),
    .irq_in( s65 ),
    .imm( imm ),
    .reti( Reti ),
    .pc_en( pc_en ),
    .CPUInterruptEnableAddr( 16'b1101 ),
    .inputInterruptAddr( 16'b1110 ),
    .interruptRegAddr( 16'b1111 ),
    .InterruptOut( intr_reg ),
    .intr( intr ),
    .irq_lock( InterLock )
  );
  // lfsr_RandomNumberGen
  lfsr_RandomNumberGen lfsr_RandomNumberGen_i14 (
    .adrrIn( s11 ),
    .dataIn( s68 ),
    .ioW( s40 ),
    .clk( s20 ),
    .ioR( s51 ),
    .SeedAdr( 16'b1011 ),
    .RngAdr( 16'b1100 ),
    .Out( rngdat0 )
  );
  // timer
  timer timer_i15 (
    .dOut( s1 ),
    .Addr( s11 ),
    .ioW( s40 ),
    .ioR( s51 ),
    .C( s20 ),
    .InterLock( InterLock ),
    .timerConfigAddr( 16'b10 ),
    .timerTargetAddr( 16'b11 ),
    .timerResetAddr( 16'b100 ),
    .timerReadAddr( 16'b101 ),
    .timerSyncStartAddr( 16'b1010 ),
    .rst_n( rst_n ),
    .TimerOut( timerdat1 ),
    .timer_interrupt( s66 )
  );
  // timer_tiny
  timer_tiny timer_tiny_i16 (
    .dOut( s69 ),
    .Addr( s11 ),
    .ioW( s40 ),
    .ioR( s51 ),
    .C( s20 ),
    .InterLock( InterLock ),
    .timerConfigAddr( 16'b1001 ),
    .timerTargetAddr( 16'b1000 ),
    .timerResetAddr( 16'b111 ),
    .timerReadAddr( 16'b110 ),
    .timerSyncStartAddr( 16'b1010 ),
    .rst_n( rst_n ),
    .TimerOut( timerdat2 ),
    .timer_interrupt( s67 )
  );
  // RegisterBlock
  RegisterBlock RegisterBlock_i17 (
    .DataIn( s13 ),
    .WE( WE ),
    .clk( s20 ),
    .src( s8 ),
    .Dest( s9 ),
    .RDest( s0 ),
    .Rsrc( s1 )
  );
  Mux_16x1_NBits #(
    .Bits(16)
  )
  Mux_16x1_NBits_i18 (
    .sel( s70 ),
    .in_0( inputReg ),
    .in_1( outR ),
    .in_2( timerdat1 ),
    .in_3( timerdat1 ),
    .in_4( timerdat1 ),
    .in_5( i2cDat ),
    .in_6( timerdat2 ),
    .in_7( timerdat2 ),
    .in_8( timerdat2 ),
    .in_9( 16'b0 ),
    .in_10( 16'b0 ),
    .in_11( rngdat0 ),
    .in_12( rngdat0 ),
    .in_13( intr_reg ),
    .in_14( intr_reg ),
    .in_15( intr_reg ),
    .out( iow_Din )
  );
  // i2c_master_ctrl
  i2c_master_ctrl i2c_master_ctrl_i19 (
    .clk( s20 ),
    .rst_n( rst_n ),
    .wr_en( s40 ),
    .reg_addr( s71 ),
    .cpu_din( s1 ),
    .sda_in( \sda-in  ),
    .scl_in( \scl-in  ),
    .cpu_dout( i2cDat ),
    .sda_out( sda_o ),
    .scl_out( scl_o ),
    .sda_oe( sda_oe ),
    .scl_oe( scl_oe ),
    .interrupt( i2c_inter )
  );
  assign s37 = (intr & \execute-pulse );
  assign outR[7:0] = uo_out_temp;
  assign outR[15:8] = 8'b0;
  assign pc_en = (~ s54 & \execute-pulse );
  assign uio_oe[0] = 1'b0;
  assign uio_oe[1] = 1'b1;
  assign uio_oe[2] = 1'b1;
  assign uio_oe[3] = 1'b1;
  assign uio_oe[4] = 1'b1;
  assign uio_oe[5] = sda_oe;
  assign uio_oe[6] = scl_oe;
  assign uio_oe[7] = 1'b0;
  // is_different
  is_different is_different_i20 (
    .in1( s48 ),
    .in2( s50 ),
    .different( s49 )
  );
  Mux_2x1 Mux_2x1_i21 (
    .sel( spi_target ),
    .in_0( 1'b1 ),
    .in_1( spi_cs ),
    .out( spics_ram )
  );
  assign s72 = ~ spi_target;
  assign s8 = s7[3:0];
  assign s9 = s7[7:4];
  assign OPcode = s7[15:8];
  assign s42 = s1[7:0];
  assign s19 = s7[7:0];
  assign s69 = s1[8:0];
  assign s68 = s1[7:0];
  assign s64 = s1[3:0];
  singExtend singExtend_i22 (
    .inst( s19 ),
    .\4S ( s3 ),
    .\8SD ( s4 ),
    .\4D ( s5 )
  );
  assign s65[0] = s49;
  assign s65[1] = s66;
  assign s65[2] = s67;
  assign s65[3] = i2c_inter;
  Mux_2x1 Mux_2x1_i23 (
    .sel( s72 ),
    .in_0( 1'b1 ),
    .in_1( spi_cs ),
    .out( spics_flash )
  );
  assign s21 = OPcode[6:0];
  assign imm = OPcode[7];
  Mux_2x1_NBits #(
    .Bits(7)
  )
  Mux_2x1_NBits_i24 (
    .sel( imm ),
    .in_0( s21 ),
    .in_1( 7'b0 ),
    .out( s22 )
  );
  assign uio_out[0] = 1'b0;
  assign uio_out[1] = spics_ram;
  assign uio_out[2] = spics_flash;
  assign uio_out[3] = spi_mosi_ram;
  assign uio_out[4] = spi_clock_ram;
  assign uio_out[5] = sda_o;
  assign uio_out[6] = scl_o;
  assign uio_out[7] = 1'b0;
  // opcode_microcode_rom
  opcode_microcode_rom opcode_microcode_rom_i25 (
    .opcode( s22 ),
    .muxb0( s25 ),
    .muxb1( s24 ),
    .muxb2( s23 ),
    .aluop0( s31 ),
    .aluop1( s30 ),
    .aluop2( s29 ),
    .aluop3( s28 ),
    .aluop4( s27 ),
    .aluop5( s26 ),
    .WE( s55 ),
    .sf( s56 ),
    .iem0( s36 ),
    .iem1( s35 ),
    .br0( s34 ),
    .br1( s33 ),
    .br2( s32 ),
    .muxA( muxA ),
    .ld( ld ),
    .st( st ),
    .abs( abs ),
    .ioW( s57 ),
    .ioR( s58 ),
    .stPC( stPC ),
    .Reti( Reti )
  );
  Mux_2x1_NBits #(
    .Bits(16)
  )
  Mux_2x1_NBits_i26 (
    .sel( muxA ),
    .in_0( s0 ),
    .in_1( s1 ),
    .out( s2 )
  );
  assign muxB[0] = s23;
  assign muxB[1] = s24;
  assign muxB[2] = s25;
  assign aluOp[0] = s26;
  assign aluOp[1] = s27;
  assign aluOp[2] = s28;
  assign aluOp[3] = s29;
  assign aluOp[4] = s30;
  assign aluOp[5] = s31;
  assign br[0] = s32;
  assign br[1] = s33;
  assign br[2] = s34;
  assign iem[0] = s35;
  assign iem[1] = s36;
  assign s38 = (\execute-pulse  & Reti);
  assign s52 = (ld & \execute-pulse );
  assign s53 = (\execute-pulse  & st);
  assign WE = ((~ ld & \execute-pulse  & s55) | (s55 & data_done & ld));
  assign sf = (s56 & \execute-pulse );
  assign s40 = (s57 & \execute-pulse );
  assign s51 = (s58 & \execute-pulse );
  assign s46 = (abs & \execute-pulse );
  Mux_8x1_NBits #(
    .Bits(16)
  )
  Mux_8x1_NBits_i27 (
    .sel( muxB ),
    .in_0( s1 ),
    .in_1( 16'b0 ),
    .in_2( ImmReg ),
    .in_3( 16'b0 ),
    .in_4( 16'b0 ),
    .in_5( s3 ),
    .in_6( s4 ),
    .in_7( s5 ),
    .out( s6 )
  );
  // muxEncoder
  muxEncoder muxEncoder_i28 (
    .a( 1'b0 ),
    .b( ld ),
    .c( s51 ),
    .d( stPC ),
    .Q( s10 )
  );
  assign s14 = br[1:0];
  Mux_4x1 Mux_4x1_i29 (
    .sel( s14 ),
    .in_0( 1'b0 ),
    .in_1( s15 ),
    .in_2( s16 ),
    .in_3( s17 ),
    .out( s18 )
  );
  Alu Alu_i30 (
    .A( s2 ),
    .B( s6 ),
    .carryIn( s15 ),
    .AluOp( aluOp ),
    .Out( s11 ),
    .Neg( s43 ),
    .Zero( s44 ),
    .CarryOut( s45 )
  );
  Mux_4x1_NBits #(
    .Bits(16)
  )
  Mux_4x1_NBits_i31 (
    .sel( s10 ),
    .in_0( s11 ),
    .in_1( mem_out ),
    .in_2( iow_Din ),
    .in_3( s12 ),
    .out( s13 )
  );
  CompSigned #(
    .Bits(16)
  )
  CompSigned_i32 (
    .a( s11 ),
    .b( 16'b1 ),
    .\= ( s39 )
  );
  assign s47 = ((s18 ^ br[2]) & \execute-pulse );
  assign s70 = s11[3:0];
  assign s71 = s11[3:0];
  assign s41 = (s39 & s40);
  assign uo_out = uo_out_temp;
endmodule
